Repository LatyshevDD/ProCharity, pull requests merged in 2023-07, with the labels that each got.

#39 Feat/content css 23 cohort
  src/styles/content.css
Labels: feat

#70 fix исправлено позиционирование popup__btn_close и параметры popup_ty…
  .gitignore
  src/blocks/popup/_type/popup_type_message.css
  src/lk-social.html
  src/styles/content.css
Labels: fix

#81 fix: на страницах с выбором даты тип input изменен на date, реализова…
  src/blocks/input/__field/_type/input__field_type_calendar.css
  src/components/FieldDate.js
  src/components/MobileMenu.js
  src/index.html
  src/lk-personal-data.html
  src/registration-npo-legal.html
  src/scripts/index.js
  src/ui-kit.html
Labels: fix

#91 (fix/misprints-readme) Исправлены опечатки в README, дополнен раздел с целями проекта
  README.md
Labels: feat, fix

#97 (fix/field-autosize) добавлен класс textarea__field_autosize на странице отзыва о вол…
  src/lk-volunteer-review.html
Labels: fix

#86 fix: убрать дефолтные стрелочки у полей с типом number + добавить в ui-kit
  src/blocks/input/__field/_type/input__field_type_number.css
  src/lk-fund-hours.html
  src/styles/content.css
  src/ui-kit.html
Labels: fix

#98 fix: В сгрупированных полях не работает очистка, нет кнопки очистки н…
  src/lk-portfolio.html
  src/ui-kit.html
Labels: fix

#104 fix: реализовано возвращение высоты поля к дефолтному значению после удаления текста
  src/components/FieldTextCleaner.js
  src/lk-portfolio.html
Labels: fix

#100 fix: добавить # в атрибут href класса sidebar__description
  src/lk-competencies.html
  src/lk-motivation.html
  src/lk-personal-data.html
  src/lk-portfolio.html
  src/lk-social.html
  src/ui-kit.html
Labels: fix

#108 fix: удален лишний label
  src/lk-npo-links.html
Labels: fix

#106 fix: исправлен тип у поля с датой на странице lk-npo-legal
  src/lk-npo-legal.html
Labels: fix

#109 fix: добавлены пропущенные закрывающие теги
  src/lk-fund-review.html
Labels: fix

#78 fix: применены корректные классы для выравнивания текста в инпутах без лейблов
  src/lk-personal-data.html
  src/lk-portfolio.html
  src/lk-social.html
  src/registration-new-volunteer.html
  src/settings-change-password.html
  src/ui-kit.html
Labels: fix

#111 fix: исправлены кнопки статуса профиля
  src/lk-access.html
  src/lk-change-password.html
  src/lk-competencies.html
  src/lk-donations.html
  src/lk-motivation.html
  src/lk-npo-contacts.html
  src/lk-npo-description.html
  src/lk-npo-documents.html
  src/lk-npo-legal.html
  src/lk-npo-links.html
  src/lk-personal-data.html
  src/lk-portfolio.html
  src/lk-social.html
  src/registration-npo-decription.html
  src/registration-npo-documents.html
  src/registration-npo-legal.html
  src/registration-npo-links.html
  src/settings-change-password.html
  src/settings-notifications.html
  src/settings-profile.html
  src/ui-kit.html
Labels: fix

#122 fix: Исправить кнопку Отмена и работу галочек #117
  src/lk-fund-hours.html
  src/lk-fund-rate.html
  src/lk-volunteer-rate.html
  src/lk-volunteer-review.html
Labels: fix

#126 fix: Поправить отступы #124
  src/lk-fund-hours.html
  src/lk-volunteer-review.html
Labels: fix

#121 Fix/add elements text
  src/lk-fund-hours.html
  src/lk-fund-rate.html
  src/lk-fund-review.html
  src/lk-volunteer-rate.html
  src/lk-volunteer-review.html
Labels: fix

#125 Исправил высоту отступов и высоту элементов на страницах отзывов воло…
  src/blocks/fieldset/_pb/fieldset_pb_mobile.css
  src/blocks/textarea/__field/textarea__field.css
  src/lk-fund-review.html
  src/lk-volunteer-review.html
  src/scripts/textarea-autosize.js
  src/styles/content.css
Labels: fix

#129 fix: check and fix text-content
  src/lk-volunteer-rate.html
  src/lk-volunteer-review.html
Labels: fix

#123 fix: заменить шрифт на Raleway
  src/blocks/custom-select/__list/custom-select__list.css
  src/blocks/footer/__logo-text/footer__logo-text.css
  src/blocks/page/page.css
  src/ui-kit.html
  src/vendor/fonts.css
Labels: fix

#119 fix: исправить адаптацию для 320px
  src/blocks/avatar/__container/avatar__container.css
  src/blocks/avatar/__label/avatar__label.css
  src/blocks/avatar/avatar.css
  src/blocks/footer/footer.css
  src/blocks/header/header.css
  src/lk-npo-contacts.html
  src/lk-personal-data.html
Labels: fix

#133 fix: добавлен модификатор для пункта меню sidebar-nav
  src/lk-volunteer-rate.html
Labels: fix

#137 fix: замена шрифта Raleway на Arial
  src/blocks/custom-select/__list/custom-select__list.css
  src/blocks/footer/__logo-text/footer__logo-text.css
  src/blocks/page/page.css
  src/styles/content.css
  src/styles/layout.css
  src/ui-kit.html
  src/vendor/fonts.css
  src/vendor/fonts/Raleway/Raleway-Bold.woff
  src/vendor/fonts/Raleway/Raleway-Bold.woff2
  src/vendor/fonts/Raleway/Raleway-Regular.woff
  src/vendor/fonts/Raleway/Raleway-Regular.woff2
  src/vendor/fonts/Raleway/Raleway-SemiBold.woff
  src/vendor/fonts/Raleway/Raleway-SemiBold.woff2
Labels: fix

#144 fix: реализовать скругление бордера у input_type_error
  src/blocks/input/__field/input__field.css
  src/blocks/input/_error/input_error.css
  src/blocks/input/_type/input_type_error.css
  src/blocks/input/input.css
  src/styles/content.css
Labels: fix

#143 fix: добавить textarea__field прозрачный бордер (прыгает верстка)
  src/blocks/textarea/__field/textarea__field.css
Labels: fix

#140 fix: добавить версию corejs в babel.config
  babel.config.js
Labels: fix

#146 fix: исправить размер кнопки btn_style_telegram в мобильной версии
  src/blocks/btn/_style/btn_style_telegram.css
Labels: fix
